<a href="https://colab.research.google.com/github/yl5091/intro-numerical-methods/blob/master/power_iterations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

# Define the matrix L
def main():
  L = np.array([[0., 0., 1., 0.5],
              [1/3., 0., 0., 0.],
              [1/3., 0.5, 0., 0.5],
              [1/3., 0.5, 0., 0.]])

# Define the initial guess for the eigenvector
x = np.random.rand(L.shape[1])

# Define the tolerance and maximum number of iterations
max_iter = 2000

# Perform the power method
for i in range(max_iter):
    x_new = np.dot(L, x)
    x = x_new / np.linalg.norm(x_new)
# Print the result
    print(x)





[0.31345103 0.20790786 0.74236422 0.554453  ]
[0.88416445 0.09060572 0.42115618 0.18075206]
[0.63477702 0.36572951 0.53409787 0.4219473 ]
[0.70338434 0.19975363 0.57155655 0.37238699]
[0.753284   0.23307957 0.51746384 0.33236773]
[0.70120855 0.25754453 0.5475305  0.37707788]
[0.72474449 0.23013999 0.54256913 0.356931  ]
[0.72400807 0.24257774 0.53732373 0.35812227]
[0.71768832 0.24177513 0.54267162 0.36328469]
[0.72249237 0.2386278  0.54039686 0.35921134]
[0.72092672 0.24113992 0.54044317 0.36060696]
[0.7206256  0.24026855 0.54109145 0.36081825]
[0.72131205 0.24014577 0.54061063 0.36024865]
[0.72090715 0.24049479 0.54076372 0.36059636]
[0.72099407 0.24027978 0.54079708 0.36051586]
[0.72105247 0.24033051 0.54072727 0.36046997]
[0.72098437 0.2403582  0.54076765 0.36052714]
[0.72101603 0.24032306 0.5407594  0.36049963]
[0.72101356 0.24034013 0.54075328 0.36050238]
[0.72100588 0.24033832 0.54076016 0.36050862]
[0.72101216 0.24033452 0.54075703 0.3605033 ]
[0.72100992 0.2403378  0.54075723 